name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: {python_version}

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pip install isort
          pip install black
          pip install mypy
          pip install flake8
          pip install flake8-bugbear
          pipenv install --deploy --dev

      - run: isort --recursive --diff
      - run: black --check .
      - run: flake8
      - run: mypy
      - run: pipenv run pytest --cov --cov-fail-under=100

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t {{cookiecutter.repo_name}}:test

      - name: Smoke test docker image
        run: |
          docker run --rm {{cookiecutter.repo_name}}:test 10
